spring:
  config:
    activate:
      on-profile: dev
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
encrypt:
  key: ${ENCRYPT_SECRET_KEY}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
