spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          default-label: main
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
encrypt:
  key: secretkey
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
