server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lotteon2/lotdiz-config
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PERSONAL_ACCESS_TOKEN}
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
encrypt:
  key: ${ENCRYPT_KEY}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: health, info, busrefresh
